### YamlMime:ModuleUnit
uid: learn.github.azure-devops-to-github-enterprise-migrations-part-ii-assessment-setup.source-environment-assessment
title: Phase 2 - Source Environment Assessment
metadata:
  title: Phase 2 - Source Environment Assessment
  description: This content is a part of the Azure Devops to GitHub Enterprise Migrations Part II - Source Environment Assessment and Target Environment Setup.
  author: camihmerhar
  ms.author: camhernandez
  ms.date: 10/17/2025
  ms.topic: unit
durationInMinutes: 5
content: |
  [!include[](includes/2-source-environment-assessment.md)]