### YamlMime:ModuleUnit
uid: learn.wwl.integrate-azure-pipelines.introduction
title: Introduction
metadata:
  title: Introduction
  description: "Explore advanced Azure Pipelines integration concepts including pipeline anatomy, templates, YAML resources, and multi-repository workflows."
  ms.date: 09/29/2025
  author: LuizMacedo
  ms.author: lumac
  ms.topic: unit
  ms.custom:
    - N/A
durationInMinutes: 1
content: |
  [!include[](includes/1-introduction.md)]
