### YamlMime:ModuleUnit
uid: learn.wwl.integrate-azure-pipelines.describe-anatomy-of-pipeline
title: Describe the anatomy of a pipeline
metadata:
  title: Describe the anatomy of a pipeline
  description: "Understand the core components and structure of Azure Pipelines, including triggers, stages, jobs, and steps that form the foundation of CI/CD workflows."
  ms.date: 09/29/2025
  author: LuizMacedo
  ms.author: lumac
  ms.topic: unit
  ms.custom:
    - N/A
durationInMinutes: 6
content: |
  [!include[](includes/2-describe-anatomy-of-pipeline.md)]
