### YamlMime:ModuleUnit
uid: learn.wwl.integrate-azure-pipelines.detail-templates
title: Detail Templates
metadata:
  title: Detail Templates
  description: "Detail templates"
  ms.date: 09/26/2025
  author: LuizMacedo
  ms.author: lumac
  ms.topic: unit
  ms.custom:
    - N/A
durationInMinutes: 3
content: |
  [!include[](includes/4-detail-templates.md)]
