### YamlMime:ModuleUnit
uid: learn.wwl.integrate-azure-pipelines.explore-yaml-resources
title: Explore YAML Resources
metadata:
  title: Explore YAML Resources
  description: "Learn how to define and use YAML resources in Azure Pipelines to manage external dependencies, repositories, and shared components efficiently."
  ms.date: 09/26/2025
  author: LuizMacedo
  ms.author: lumac
  ms.topic: unit
  ms.custom:
    - N/A
durationInMinutes: 2
content: |
  [!include[](includes/5-explore-yaml-resources.md)]
