### YamlMime:ModuleUnit
uid: learn.wwl.integrate-azure-pipelines.use-multiple-repositories-your-pipeline
title: Use Multiple Repositories in Your Pipeline
metadata:
  title: Use Multiple Repositories in Your Pipeline
  description: "Learn how to configure and manage multiple repositories in Azure Pipelines to support complex projects with distributed codebases and shared components."
  ms.date: 09/26/2025
  author: LuizMacedo
  ms.author: lumac
  ms.topic: unit
  ms.custom:
    - N/A
durationInMinutes: 3
content: |
  [!include[](includes/6-use-multiple-repositories-your-pipeline.md)]
