### YamlMime:ModuleUnit
uid: learn.wwl.integrate-azure-pipelines.migrate-pipeline-classic-yaml-azure-pipelines
title: Migrate a pipeline from classic to YAML in Azure Pipelines
metadata:
  title: Migrate a pipeline from classic to YAML in Azure Pipelines
  description: "Migrate a pipeline from classic to YAML in Azure Pipelines"
  ms.date: 09/29/2025
  author: LuizMacedo
  ms.author: lumac
  ms.topic: unit
durationInMinutes: 3
content: |
  [!include[](includes/7-migrate-pipeline-classic-yaml-azure-pipelines.md)]
