### YamlMime:ModuleUnit
uid: learn.wwl.integrate-azure-pipelines.summary
title: Summary
metadata:
  title: Summary
  description: "Key concepts and next steps for Azure Pipelines integration"
  ms.date: 09/26/2025
  author: LuizMacedo
  ms.author: lumac
  ms.topic: unit
durationInMinutes: 1
content: |
  [!include[](includes/9-summary.md)]
