### YamlMime:Module
uid: learn.wwl.integrate-azure-pipelines
metadata:
  title: Integrate with Azure Pipelines
  description: "Learn Azure Pipelines integration by exploring advanced pipeline anatomy, structure, templates, YAML resources, and multi-repository workflows for comprehensive CI/CD solutions."
  ms.date: 09/29/2025
  author: LuizMacedo
  ms.author: lumac
  ms.topic: module
  ms.custom:
    - N/A
  ms.service: azure
  ai-usage: ai-assisted
title: Integrate with Azure Pipelines
summary: Learn Azure Pipelines integration by exploring advanced pipeline anatomy, structure, templates, YAML resources, and multi-repository workflows. Build effective CI/CD solutions using modern pipeline practices.
abstract: |
  By the end of this module, you're able to:

  -   Understand advanced Azure Pipelines anatomy and structure

  -   Create and use pipeline templates for code reuse

  -   Work with YAML resources and dependencies

  -   Implement multi-repository workflows in your pipelines

  -   Apply modern pipeline integration patterns and best practices
prerequisites: None
iconUrl: /training/achievements/6-integrate-with-azure-pipelines.svg
levels:
  - advanced
roles:
  - administrator
  - ai-engineer
  - data-engineer
  - developer
  - devops-engineer
  - platform-engineer
  - security-engineer
  - security-operations-analyst
  - service-adoption-specialist
  - solution-architect
  - startup-founder
  - technology-manager
products:
  - azure
  - azure-artifacts
  - azure-boards
  - azure-cloud-services
  - azure-devops
  - azure-pipelines
  - azure-repos
  - azure-test-plans
  - github
subjects:
  - devops
units:
  - learn.wwl.integrate-azure-pipelines.introduction
  - learn.wwl.integrate-azure-pipelines.describe-anatomy-of-pipeline
  - learn.wwl.integrate-azure-pipelines.understand-pipeline-structure
  - learn.wwl.integrate-azure-pipelines.detail-templates
  - learn.wwl.integrate-azure-pipelines.explore-yaml-resources
  - learn.wwl.integrate-azure-pipelines.use-multiple-repositories-your-pipeline
  - learn.wwl.integrate-azure-pipelines.migrate-pipeline-classic-yaml-azure-pipelines
  - learn.wwl.integrate-azure-pipelines.knowledge-check
  - learn.wwl.integrate-azure-pipelines.summary
badge:
  uid: learn.wwl.integrate-azure-pipelines.badge
