### YamlMime:ModuleUnit
uid: learn.wwl.implement-bicep.azure-deployment-use-resource-manager-templates
title: Deployments Using Azure Bicep Templates
metadata:
  title: Deployments Using Azure Bicep Templates
  description: "Understand how Bicep integrates with Azure Resource Manager, the deployment process, and best practices for production deployments."
  ms.date: 10/08/2025
  author: LuizMacedo
  ms.author: lumac
  ms.topic: unit
  ms.custom:
    - sfi-ga-nochange
    - devx-track-bicep
    - N/A
durationInMinutes: 60
content: |
  [!include[](includes/8-azure-deployment-use-resource-manager-templates.md)]
