### YamlMime:ModuleUnit
uid: learn.wwl.automate-inspection-of-health.configure-github-notifications
title: Configure GitHub Notifications
metadata:
  title: Configure GitHub Notifications
  description: "Set up GitHub notification systems for repository events, pull requests, and workflow monitoring"
  ms.date: 10/01/2025
  author: LuizMacedo
  ms.author: lumac
  ms.topic: unit
  ms.custom:
    - N/A
durationInMinutes: 2
content: |
  [!include[](includes/6-configure-github-notifications.md)]
