### YamlMime:ModuleUnit
uid: learn.wwl.manage-git-repositories.configure-source-control-repository-permissions-use-github
title: Configure repository permissions using GitHub
metadata:
  title: Configure repository permissions using GitHub
  description: "Learn how to set up repository permissions and access controls in GitHub"
  ms.date: 09/05/2024
  author: LuizMacedo
  ms.author: lumac
  ms.topic: unit
  ms.custom:
    - N/A
durationInMinutes: 3
content: |
  [!include[](includes/12-configure-source-control-repository-permissions-use-github.md)]
