### YamlMime:ModuleUnit
uid: learn.wwl.manage-git-repositories.configure-github-tags-organize-repositories
title: Configure GitHub tags to organize repositories
metadata:
  title: Configure GitHub tags to organize repositories
  description: "Learn how to use GitHub tags to organize and track your project's development milestones"
  ms.date: 09/05/2024
  author: LuizMacedo
  ms.author: lumac
  ms.topic: unit
  ms.custom:
    - N/A
durationInMinutes: 3
content: |
  [!include[](includes/13-configure-github-tags-organize-repositories.md)]
