### YamlMime:ModuleUnit
uid: learn.wwl.security-monitoring-and-governance.configure-github-advanced-security-github
title: Configure GitHub Advanced Security for GitHub and Azure DevOps
metadata:
  title: Configure GitHub Advanced Security for GitHub and Azure DevOps
  description: Configure GitHub Advanced Security in GitHub including CodeQL code scanning workflows, secret scanning with push protection, Dependabot dependency scanning and automated updates, dependency review in pull requests, custom patterns, and security policies for comprehensive repository protection.
  ms.date: 10/28/2025
  author: LuizMacedo
  ms.author: lumac
  ms.topic: unit
  ms.custom:
    - N/A
durationInMinutes: 15
content: |
  [!include[](includes/11-configure-github-advanced-security-github.md)]
