### YamlMime:ModuleUnit
uid: learn.wwl.security-monitoring-and-governance.implement-pipeline-security
title: Implement pipeline security
metadata:
  title: Implement Pipeline Security
  description: "Implement comprehensive pipeline security with secrets management, service connection security, RBAC, agent security, deployment gates, audit logging, and security scanning integration."
  ms.date: 10/28/2025
  author: LuizMacedo
  ms.author: lumac
  ms.topic: unit
  ms.custom:
    - N/A
durationInMinutes: 14
content: |
  [!include[](includes/2-implement-pipeline-security.md)]
