### YamlMime:ModuleUnit
uid: learn.wwl.configure-provision-environments.provision-configure-target-environments
title: Provision and configure target environments
metadata:
  title: Provision and configure target environments
  description: "Learn to provision and configure deployment target environments for application releases."
  ms.date: 10/01/2025
  author: LuizMacedo
  ms.author: lumac
  ms.topic: unit
  ms.custom:
    - N/A
durationInMinutes: 5
content: |
  [!include[](includes/2-provision-configure-target-environments.md)]
