### YamlMime:ModuleUnit
uid: learn.wwl.configure-provision-environments.configure-automated-integration-functional-test-automation
title: Configure automated integration and functional test automation
metadata:
  title: Configure automated integration and functional test automation
  description: "Implement automated integration testing and functional test automation in deployment pipelines."
  ms.date: 10/01/2025
  author: LuizMacedo
  ms.author: lumac
  ms.topic: unit
  ms.custom:
    - N/A
durationInMinutes: 6
content: |
  [!include[](includes/4-configure-automated-integration-functional-test-automation.md)]
