### YamlMime:ModuleUnit
uid: learn.wwl.implement-pipeline-strategy.configure-agent-demands
title: Configure Agent Demands
metadata:
  title: Configure Agent Demands
  description: "Learn how to configure agent demands to ensure your pipeline jobs run on agents with the right capabilities and resources."
  ms.date: 09/25/2025
  author: LuizMacedo
  ms.author: lumac
  ms.topic: unit
  ms.custom:
    - N/A
durationInMinutes: 5
content: |
  [!include[](includes/2-configure-agent-demands.md)]
