### YamlMime:ModuleUnit
uid: learn.wwl.implement-pipeline-strategy.explore-multi-configuration-multi-agent
title: Explore Multi-Configuration and Multi-Agent Builds
metadata:
  title: Explore Multi-Configuration and Multi-Agent Builds
  description: "Discover how to implement multi-configuration and multi-agent builds to test across different environments and platforms simultaneously."
  ms.date: 09/25/2025
  author: LuizMacedo
  ms.author: lumac
  ms.topic: unit
  ms.custom:
    - N/A
durationInMinutes: 5
content: |
  [!include[](includes/3-explore-multi-configuration-multi-agent.md)]
