### YamlMime:ModuleUnit
uid: learn.wwl.implement-pipeline-strategy.explore-source-control-types-supported-by-azure-pipelines
title: Explore Source Control Types Supported by Azure Pipelines
metadata:
  title: Explore Source Control Types Supported by Azure Pipelines
  description: "Discover the various source control systems that Azure Pipelines supports and how to integrate them effectively into your CI/CD workflows."
  ms.date: 09/26/2025
  author: LuizMacedo
  ms.author: lumac
  ms.topic: unit
  ms.custom:
    - N/A
durationInMinutes: 3
content: |
  [!include[](includes/8-explore-source-control-types-supported-by-azure-pipelines.md)]
