### YamlMime:ModuleUnit
uid: learn.wwl.plan-agile-github-projects-azure-boards.configure-projects-teams-azure-devops
title: Configure projects and teams in Azure DevOps
metadata:
  title: Configure projects and teams in Azure DevOps
  description: "Configure projects and teams in Azure DevOps"
  ms.date: 09/02/2025
  author: LuizMacedo
  ms.author: lumac
  ms.topic: unit
durationInMinutes: 3
content: |
  [!include[](includes/4-configure-projects-teams-azure-devops.md)]
