### YamlMime:ModuleUnit
uid: learn.wwl.plan-agile-github-projects-azure-boards.configure
title: Configure GitHub Projects
metadata:
  title: Configure GitHub Projects
  description: "Configure GitHub Projects"
  ms.date: 09/02/2025
  author: LuizMacedo
  ms.author: lumac
  ms.topic: unit
durationInMinutes: 3
content: |
  [!include[](includes/6-configure.md)]
