### YamlMime:ModuleUnit
uid: learn.wwl.manage-azure-pipeline-agents-pools.communicate-with-azure-pipelines
title: Communicate with Azure Pipelines
metadata:
  title: Communicate with Azure Pipelines
  description: "Learn how agents establish and maintain communication with Azure Pipelines service for secure and reliable pipeline execution."
  ms.date: 09/25/2025
  author: LuizMacedo
  ms.author: lumac
  ms.topic: unit
  ms.custom:
    - N/A
durationInMinutes: 4
content: |
  [!include[](includes/7-communicate-with-azure-pipelines.md)]
