### YamlMime:ModuleUnit
uid: learn.wwl.implement-desired-state-configuration-dsc.understand-configuration-drift
title: Understand configuration drift
metadata:
  title: Understand Configuration Drift
  description: "Learn about configuration drift, its causes, and how it impacts infrastructure consistency and reliability over time."
  ms.date: 10/08/2025
  author: LuizMacedo
  ms.author: lumac
  ms.topic: unit
  ms.custom:
    - N/A
durationInMinutes: 3
content: |
  [!include[](includes/2-understand-configuration-drift.md)]
