### YamlMime:ModuleUnit
uid: learn.wwl.implement-desired-state-configuration-dsc.explore-desired-state-configuration-dsc
title: Explore Desired State Configuration (DSC)
metadata:
  title: Explore Desired State Configuration (DSC)
  description: "Explore DSC components including configurations, resources, and Local Configuration Manager (LCM), plus push and pull deployment modes."
  ms.date: 10/08/2025
  author: LuizMacedo
  ms.author: lumac
  ms.topic: unit
  ms.custom:
    - N/A
durationInMinutes: 3
content: |
  [!include[](includes/3-explore-desired-state-configuration-dsc.md)]
