### YamlMime:ModuleUnit
uid: learn.wwl.implement-desired-state-configuration-dsc.explore-azure-automation
title: Explore Azure Automation State Configuration (DSC)
metadata:
  title: Explore Azure Automation State Configuration (DSC)
  description: "Learn about Azure Automation State Configuration service, including node management, configuration compilation, and monitoring capabilities."
  ms.date: 10/08/2025
  author: LuizMacedo
  ms.author: lumac
  ms.topic: unit
  ms.custom:
    - N/A
durationInMinutes: 3
content: |
  [!include[](includes/4-explore-azure-automation.md)]
