### YamlMime:ModuleUnit
uid: learn.wwl.explore-release-strategy-recommendations.control-deployments-using-release-gates
title: Control deployments using release gates
metadata:
  title: Control deployments using release gates
  description: "Configure and implement release gates to control deployment progression and ensure quality standards."
  ms.date: 10/01/2025
  author: LuizMacedo
  ms.author: lumac
  ms.topic: unit
  ms.custom:
    - N/A
durationInMinutes: 75
content: |
  [!include[](includes/7-control-deployments-using-release-gates.md)]
