### YamlMime:ModuleUnit
uid: learn.wwl.learn-continuous-integration-github-actions.examine-environment-variables
title: Examine Environment Variables
metadata:
  title: Examine Environment Variables
  description: "Learn how to configure and use environment variables in GitHub Actions workflows effectively."
  ms.date: 09/26/2025
  author: LuizMacedo
  ms.author: lumac
  ms.topic: unit
durationInMinutes: 3
content: |
  [!include[](includes/3-examine-environment-variables.md)]
