### YamlMime:ModuleUnit
uid: learn.wwl.create-release-pipeline.understand-database-deployment-task
title: Understand database deployment task
metadata:
  title: Understand database deployment task
  description: "Learn how to configure and use database deployment tasks in release pipelines."
  ms.date: 10/01/2025
  author: LuizMacedo
  ms.author: lumac
  ms.topic: unit
  ms.custom:
    - N/A
durationInMinutes: 3
content: |
  [!include[](includes/10-understand-database-deployment-task.md)]
