### YamlMime:ModuleUnit
uid: learn.wwl.create-release-pipeline.configure-pipelines-code-with-yaml
title: Configure pipelines as code with YAML
metadata:
  title: Configure pipelines as code with YAML
  description: "Learn how to configure pipelines as code using YAML."
  ms.date: 10/01/2025
  author: LuizMacedo
  ms.author: lumac
  ms.topic: unit
  ms.custom:
    - sfi-ga-nochange
    - N/A
durationInMinutes: 60
content: |
  [!include[](includes/11-configure-pipelines-code-with-yaml.md)]
