### YamlMime:ModuleUnit
uid: learn.wwl.implement-tools-to-track-usage-flow.explore-application-insights
title: Explore Application Insights
metadata:
  title: Explore Application Insights
  description: "Explore Application Insights features for application performance management (APM), including telemetry collection, live metrics, and usage analytics."
  ms.date: 10/13/2025
  author: LuizMacedo
  ms.author: lumac
  ms.topic: unit
  ms.custom:
    - N/A
durationInMinutes: 5
content: |
  [!include[](includes/6-explore-application-insights.md)]
