### YamlMime:ModuleUnit
uid: learn.wwl.implement-tools-to-track-usage-flow.implement-application-insights
title: Implement Application Insights
metadata:
  title: Implement Application Insights
  description: "Learn how to implement Application Insights in applications, configure instrumentation keys, and integrate telemetry collection into code."
  ms.date: 10/13/2025
  author: LuizMacedo
  ms.author: lumac
  ms.topic: unit
  ms.custom:
    - N/A
durationInMinutes: 4
content: |
  [!include[](includes/7-implement-application-insights.md)]
