### YamlMime:ModuleUnit
uid: learn.wwl.implement-tools-to-track-usage-flow.monitor-application-performance-app-insights
title: Monitor Application Performance with Azure Load Testing
metadata:
  title: Monitor Application Performance with Azure Load Testing
  description: "Learn how to monitor application performance using Azure Load Testing integrated with Application Insights for comprehensive performance analysis."
  ms.date: 10/13/2025
  author: LuizMacedo
  ms.author: lumac
  ms.topic: unit
  ms.custom:
    - sfi-ga-nochange
    - N/A
durationInMinutes: 60
content: |
  [!include[](includes/9-monitor-application-performance-app-insights.md)]
