### YamlMime:ModuleUnit
uid: learn.wwl.introduction-to-deployment-patterns.understand-modern-deployment-patterns
title: Understand modern deployment patterns
metadata:
  title: Understand modern deployment patterns
  description: Explore progressive delivery, feature flags, A/B testing, and advanced continuous deployment strategies for modern applications.
  ms.date: 10/23/2025
  author: LuizMacedo
  ms.author: lumac
  ms.topic: unit
  ms.custom:
    - N/A
durationInMinutes: 3
content: |
  [!include[](includes/4-understand-modern-deployment-patterns.md)]
