### YamlMime:ModuleUnit
uid: learn.wwl.manage-application-configuration-data.enable-dynamic-configuration-feature-flags
title: Enable Dynamic Configuration and Feature Flags
metadata:
  title: Enable Dynamic Configuration and Feature Flags
  description: "Hands-on lab implementing Azure App Configuration with dynamic configuration refresh and feature flag management for progressive feature rollouts"
  ms.date: 10/07/2025
  author: LuizMacedo
  ms.author: lumac
  ms.topic: unit
durationInMinutes: 60
content: |
  [!include[](includes/13-enable-dynamic-configuration-feature-flags.md)]
