### YamlMime:ModuleUnit
uid: learn.wwl.manage-application-configuration-data.rethink-application-configuration-data
title: Rethink Application Configuration Data
metadata:
  title: Rethink Application Configuration Data
  description: "Examine configuration file limitations, secret management anti-patterns, and modern externalized configuration approaches replacing traditional config file deployments"
  ms.date: 10/23/2025
  author: LuizMacedo
  ms.author: lumac
  ms.topic: unit
  ms.custom: sfi-ropc-nochange
durationInMinutes: 5
content: |
  [!include[](includes/2-rethink-application-configuration-data.md)]
