### YamlMime:ModuleUnit
uid: learn.wwl.manage-application-configuration-data.introduction-to-azure-app-configuration
title: Introduction to Azure App Configuration
metadata:
  title: Introduction to Azure App Configuration
  description: "Explore Azure App Configuration service for centralized configuration management with dynamic refresh, feature flags, and Key Vault integration"
  ms.date: 10/23/2025
  author: LuizMacedo
  ms.author: lumac
  ms.topic: unit
durationInMinutes: 3
content: |
  [!include[](includes/6-introduction-to-azure-app-configuration.md)]
