### YamlMime:ModuleUnit
uid: learn.wwl.manage-application-configuration-data.integrate-azure-key-vault-azure-pipelines
title: Integrate Azure Key Vault with Azure Pipelines
metadata:
  title: Integrate Azure Key Vault with Azure Pipelines
  description: "Integrate Azure Key Vault with Azure Pipelines for secure secret retrieval using service connections and AzureKeyVault task implementations"
  ms.date: 10/24/2025
  author: LuizMacedo
  ms.author: lumac
  ms.topic: unit
durationInMinutes: 2
content: |
  [!include[](includes/9-integrate-azure-key-vault-azure-pipelines.md)]
