### YamlMime:ModuleUnit
uid: learn.wwl.identify-technical-debt.introduction-to-github-advanced-security
title: Introduction to GitHub Advanced Security
metadata:
  title: Introduction to GitHub Advanced Security
  description: "Discover how GitHub Advanced Security helps you find security issues that can become technical debt."
  ms.date: 09/08/2025
  author: LuizMacedo
  ms.author: lumac
  ms.topic: unit
  ms.custom:
    - N/A
durationInMinutes: 3
content: |
  [!include[](includes/6-introduction-to-github-advanced-security.md)]
