### YamlMime:ModuleUnit
uid: learn.wwl.describe-pipelines-concurrency.describe-azure-pipelines-open-source-projects
title: Describe Azure Pipelines and open-source projects
metadata:
  title: Describe Azure Pipelines And Open-Source Projects
  description: "Explore how Azure Pipelines supports open-source projects with free parallel jobs and community-friendly features."
  ms.date: 09/26/2025
  author: LuizMacedo
  ms.author: lumac
  ms.topic: unit
  ms.custom:
    - N/A
durationInMinutes: 6
content: |
  [!include[](includes/4-describe-azure-pipelines-open-source-projects.md)]
