### YamlMime:ModuleUnit
uid: learn.wwl.describe-pipelines-concurrency.explore-azure-pipelines-visual-designer
title: Explore Azure Pipelines and Visual Designer
metadata:
  title: Explore Azure Pipelines And Visual Designer
  description: "Discover the Visual Designer interface for creating and managing Azure Pipelines through a graphical user interface."
  ms.date: 09/25/2025
  author: LuizMacedo
  ms.author: lumac
  ms.topic: unit
  ms.custom:
  - N/A
durationInMinutes: 4
content: |
  [!include[](includes/5-explore-azure-pipelines-visual-designer.md)]
