### YamlMime:ModuleUnit
uid: learn.wwl.describe-pipelines-concurrency.describe-azure-pipelines-yaml
title: Describe Azure Pipelines and YAML
metadata:
  title: Describe Azure Pipelines And YAML
  description: "Learn how to define Azure Pipelines using YAML syntax for version-controlled, code-based CI/CD configurations."
  ms.date: 09/26/2025
  author: LuizMacedo
  ms.author: lumac
  ms.topic: unit
  ms.custom:
    - N/A
durationInMinutes: 4
content: |
  [!include[](includes/6-describe-azure-pipelines-yaml.md)]
