### YamlMime:ModuleUnit
uid: learn.wwl.describe-pipelines-concurrency.enable-continuous-integration-azure-pipelines
title: Enable Continuous Integration with Azure Pipelines
metadata:
  title: Enable Continuous Integration With Azure Pipelines
  description: "Set up and configure continuous integration workflows using Azure Pipelines to automate build and testing processes."
  ms.date: 09/25/2025
  author: LuizMacedo
  ms.author: lumac
  ms.topic: unit
  ms.custom:
  - N/A
durationInMinutes: 45
content: |
  [!include[](includes/7-enable-continuous-integration-azure-pipelines.md)]
